//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivideAndConquerTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DivideAndConquerTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54044
        ///14108
        ///79294
        ///29649
        ///25260
        ///60660
        ///2995
        ///53777
        ///49689
        ///9083
        ///16122
        ///90436
        ///4615
        ///40660
        ///25675
        ///58943
        ///92904
        ///9900
        ///95588
        ///46120
        ///29390
        ///91323
        ///85363
        ///45738
        ///80717
        ///57415
        ///7637
        ///8540
        ///6336
        ///45434
        ///65895
        ///61811
        ///8959
        ///9139
        ///31027
        ///87662
        ///2484
        ///65550
        ///23260
        ///15616
        ///3490
        ///49568
        ///5979
        ///44737
        ///52808
        ///72122
        ///37957
        ///34826
        ///21419
        ///73531
        ///94323
        ///52910
        ///84496
        ///71799
        ///50162
        ///1692
        ///1565
        ///59279
        ///56864
        ///20141
        ///13893
        ///63942
        ///6055
        ///33424
        ///44771
        ///25678
        ///33639
        ///27793
        ///41268
        ///1857
        ///63388
        ///32976
        ///46195
        ///61291
        ///61740
        ///616 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntegerArray {
            get {
                return ResourceManager.GetString("IntegerArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2148
        ///9058
        ///7742
        ///3153
        ///6324
        ///609
        ///7628
        ///5469
        ///7017
        ///504
        ///4092
        ///1582
        ///9572
        ///1542
        ///5697
        ///2081
        ///4218
        ///3130
        ///7923
        ///9595
        ///6558
        ///3859
        ///9832
        ///3062
        ///6788
        ///7578
        ///7432
        ///479
        ///8439
        ///9079
        ///7173
        ///2667
        ///2770
        ///2655
        ///972
        ///4264
        ///2014
        ///3171
        ///4715
        ///345
        ///4388
        ///3816
        ///8887
        ///3915
        ///3490
        ///2327
        ///123
        ///4596
        ///4307
        ///8737
        ///4007
        ///6798
        ///6551
        ///1627
        ///1190
        ///4984
        ///2480
        ///3404
        ///2027
        ///4778
        ///2951
        ///2795
        ///5002
        ///8121
        ///8910
        ///9593
        ///5254
        ///448
        ///6237
        ///5565
        ///1816
        ///392
        ///8143
        ///9310
        ///9293
        ///3138
        ///4869
        ///6756
        ///872
        ///6183
        ///3517
        ///3513
        ///1676
        ///5498
        ///9172
        ///5739
        ///6108        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuickSort {
            get {
                return ResourceManager.GetString("QuickSort", resourceCulture);
            }
        }
    }
}
